services:

  spring-boot-kafka-consumer-1:
    build: .
    image: rupendra1817/spring-boot-kafka-consumer:1.0
    container_name: kafka-consumer-app

    ports:
      - "8083:8080"

    restart: unless-stopped

    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka42:29092

    networks:
      - kafka-network

networks:
  kafka-network:
    external: true